language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

install: travis_retry composer install

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
script:
  - phpunit --coverage-clover coverage.clover
after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
